### ISSUE TITLE
Support lodash/fp?

### ISSUE THREAD

**Issue by jorgegonzalez** [villesau/optional-chaining-codemod#18]
Hi, thanks for making this!

The get function from lodash/fp flips the arguments. Would it be possible to support this?

https://github.com/lodash/lodash/wiki/FP-Guide

**Comment by villesau** [comment]
It shouldn't be hard to implement! This is where normal gets are handled: https://github.com/villesau/optional-chaining-codemod/blob/master/transform.js#L102

and here are checked different types of imports: https://github.com/villesau/optional-chaining-codemod/blob/master/transform.js#L107

I think you'd need to flip the argument order for fp, and match against `lodash/fp` I guess. Feel free to submit a pull request! :) AST explorer is your friend when developing the codemod: https://astexplorer.net/

**Comment by jorgegonzalez** [comment]
PR opened @villesau, I'd appreciate any feedback!

**Comment by villesau** [comment]
This is now published in 1.2.0, thanks for the contribution @jorgegonzalez !
