### ISSUE TITLE
how to run against typescript codebase?

### ISSUE THREAD

**Issue by sibelius** [villesau/optional-chaining-codemod#2]
congrats on this codemod

how to run against typscript codebase?

**Comment by chimurai** [comment]
Created PR #6  to add support for typescript.

For now, you do the following manual steps:

In your project root:
1. `npm install optional-chaining-codemod`
2. `npm install jscodeshift@latest`
3. `rm -rf ./node_modules/optional-chaining-codemod/node_modules/jscodeshift`

```
npm run optional-chaining-codemod ./**/*.js --parser=ts
```

```
yarn optional-chaining-codemod ./**/*.js --parser=ts
```

**Comment by villesau** [comment]
Thanks for the PR @chimurai! This is now in 0.2.0 version.
