### ISSUE TITLE
Doesn't reduce `getOr(false, ...)` correctly

### ISSUE THREAD

**Issue by daveisfera** [villesau/optional-chaining-codemod#22]
Thanks again for this awesome codemod!

`getOr(false, 'value', data)` is kind of silly, but it's reduced to `data?.value ?? false` when it should just be `data?.value` since it will already be `falsy` and `eslint` doesn't like `?? false`

**Comment by villesau** [comment]
Well that's not the whole story. If you have `{value: null}`, it would become `null` instead of `false`. In some systems this might be a bug.  It's now functionally equal to what lodash would produce. I'd say this is by design and should stay as is.

**Comment by daveisfera** [comment]
Makes sense, so I'll close this one out
