### ISSUE TITLE
can we also handle `idx` calls?

### ISSUE THREAD

**Issue by sibelius** [villesau/optional-chaining-codemod#3]
input:

`const value = idx(obj, _ => _.a.b.c)`

output:

`const value = obj?.a?.b?.c`

**Comment by jgcmarins** [comment]
> const value = (obj, _ => _.a.b.c)

you mean `const value = idx(obj, _ => _.a.b.c)`

**Comment by villesau** [comment]
@sibelius feel free to submit a pull request!

**Comment by sibelius** [comment]
related to https://github.com/cdlewis/idx-to-optional-chaining

**Comment by sibelius** [comment]
https://github.com/cdlewis/idx-to-optional-chaining is battle tested, go with it
