### ISSUE TITLE
Wrong result with `BinaryExpression` when migrate Lodash `get` calls

### ISSUE THREAD

**Issue by xyy94813** [villesau/optional-chaining-codemod#37]
Test Case: 

`_.get(object, 'property', 0) + 1`
`_.get(object, 'property', 0) > 1`

Now:

`object?.property ?? 0 + 1`
`object?.property ?? 0 > 1`

Except: 
`(object?.property ?? 0) + 1`
`(object?.property ?? 0) > 1`

**Comment by xyy94813** [comment]
https://github.com/benjamn/recast/issues/890

**Comment by villesau** [comment]
Updated jscodeshift, that might fix the issue.

**Comment by villesau** [comment]
This is now fixed by @lautis https://github.com/villesau/optional-chaining-codemod/pull/59

Thanks!
