### ISSUE TITLE
array syntax

### ISSUE THREAD

**Issue by benmonro** [villesau/optional-chaining-codemod#8]
looks like i might have found an edge case for you:

```javascript
     get(foo, 'bar[0]["60"]')
```

is transforming to 
```javascript
      foo?.bar?.0]["60"

```

**Comment by villesau** [comment]
Oh... That looks weird 😅

**Comment by villesau** [comment]
This was fixed in 0.3.0. It was due to outdated version of my sync of this file: https://github.com/lodash/lodash/blob/8b441a506ba4ea0f86f19bc0250c9ec2731b75d6/.internal/stringToPath.js
